# Site Settings
baseurl: 		""
title: 			Data for Evil

name: 			Data for Evil
description: 	Because the unreasonable effectiveness of data goes both ways
url: 			"http://localhost:4000"

paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		dataforevil
email: 			hello@indiqo.eu

disqus: 		your_disqus_shortname
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2015 DataForEvil.	

# Build Settings
permalinks: 	pretty